import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { XstateDslProtoGeneratedModule, XstateDslProtoGeneratedSharedModule } from './generated/module';
import { XstateDslProtoValidationRegistry, XstateDslProtoValidator } from './xstate-dsl-proto-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type XstateDslProtoAddedServices = {
    validation: {
        XstateDslProtoValidator: XstateDslProtoValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type XstateDslProtoServices = LangiumServices & XstateDslProtoAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const XstateDslProtoModule: Module<XstateDslProtoServices, PartialLangiumServices & XstateDslProtoAddedServices> = {
    validation: {
        ValidationRegistry: (services) => new XstateDslProtoValidationRegistry(services),
        XstateDslProtoValidator: () => new XstateDslProtoValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createXstateDslProtoServices(context?: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    XstateDslProto: XstateDslProtoServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        XstateDslProtoGeneratedSharedModule
    );
    const XstateDslProto = inject(
        createDefaultModule({ shared }),
        XstateDslProtoGeneratedModule,
        XstateDslProtoModule
    );
    shared.ServiceRegistry.register(XstateDslProto);
    return { shared, XstateDslProto };
}
